#!/bin/bash
cat << "EOF"




                                               ....,,:;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::c',.. ..
                                         . ,;oOKWWNWXWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNWXkd;',.
                                       .ck0WWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMXd:..
                                    .;OXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;.
                                  .c0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc'
                                 'XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:
                               .oOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc'
                               kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.
                             .dNMMMMMMMMMMMMMMMMMMWNWNNXKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWWWMMMMMMMMMMMMMMMMMMMWNx.
                             cNMMMMMMMMMMMMMMMMMW0o:.                                                                                                                                                                                                                          . .:kXNNMMMMMMMMMMMMMMMMMW;
                             0WMMMMMMMMMMMMMMMW0,.                                                                                                                                                                                                                                   l0NMMMMMMMMMMMMMMMMX0
                            .kNMMMMMMMMMMMMMWKd.                                                                                                                                                                                                                                      .dWMMMMMMMMMMMMMMMMX
                            .KNMMMMMMMMMMMMMWx                                                                                                                                                                                                                                         .0WMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMW;                                                                                                                                                                                                                                          :NWMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMW.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                               .,:clllllc:;'.                                                                                                                                                                             .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                          ,oONMMMMMMMMMMMMMMMMN0x:.                                ':ldxkkkkxoc;.                                                        ..,.                                                             .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                       c0MMMMMMMMMMMMMMMMMMMMMMMMMMNx.                        .ckNMMMMMMMMMMMMMMMMNOo'                                              .ckXMMMMMMXXNNWWKkl,                                                  .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                    .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,                   .oXMMMMMMMMMMMMMMMMMMMMMMMMNc                                         cOWMMMMMMMMMMMMMMMMMMMMMWMWl,.                                           .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                  .kMMMMMMMMMMMMMMMNNXXNWMMMMMMMMMMMMMMMx                ;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMK                                      lXMMMMMMMMMKdl:c;;;;:ldkKWMMMMMMMKc                                         .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                 oWMMMMMMMMMMWOc'.        ..;o0MMMMMMMMMM0             'KMMMMMMMMMMMMMNKOkkOKNMMMMMMMMO.                                   .xWMMMMMMN0x;                'oXMMMMMMWo                                       .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                               .KMMMMMMMMMM0;                  .kMMMMMMMMMk           oMMMMMMMMMMXd;.           .';;'              .                      oMMMMMMMO.                       ,0MMMMMMN,                                     .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                              'NMMMMMMMMMK'                      oMMMMMMMMM'         xMMMMMMMMWo.                                 .                      0MMMMNd'                            ;NMMMMMMl                                    .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                             ;MMMMMMMMMWc                         XMMMMMMMMx        ,MMMMMMMMM,                                  .                     .OMMMX:                                 OMMMWOX,                                   .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                            ,MMMMMMMMMN.                          lMMMMMMMMN        dMMMMMMMMMl                                 .                     cMMMN:                   .....            0MMN:.'                                   .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                            NMMMMMMMMX.                           ;MMMMMMMMM        lMMMMMMMMMMW0dlc:::;,,'...                                       ,MMMW.                .l00dl:;::;.         .WMMW..                    .              .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                           xMMMMMMMMW.                            ;MMMMMMMMM         OMMMMMMMMMMMMMMMMMMMMMMMMMN0xc'           .                    .NMMM:                oK:                    kMMW'                                    .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                          .MMMMMMMMMl                             oMMMMMMMMX          :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,                             kMMM;               .Nl                      oMMMc                      .             .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                          cMMMMMMMMW                              KMMMMMMMMk            .ckXMMMMMMMMMMMMMMMMMMMMMMMMMMMX;                           OMMX               .Xd                       lMMM0                                    .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                          xMMMMMMMMO                             ,MMMMMMMMM,                 .;codxkOOO0KKXWMMMMMMMMMMMMMx                          OMMO               dM.                       dMMO.                                    .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                          OMMMMMMMMx                             XMMMMMMMMK                                  .,dWMMMMMMMMMd                         0MMl               dMc                       OMM,                                     .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                          kMMMMMMMMk                            OMMMMMMMMM'                                     .KMMMMMMMMM.                        0MM;               ,MX                     .xMM:                                      .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                          cMMMMMMMMW.                          OMMMMMMMMMl                                       ;MMMMMMMMM:                        OMMc                lMO                    KMx;                                       .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                           WMMMMMMMMX.                       'XMMMMMMMMMd         ;lol,                          oMMMMMMMMMc                        dMMN                 'KNc               .xWXl                                         .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                           ;MMMMMMMMMWc                    .xMMMMMMMMMMl        cWMMMMMN,                      .kMMMMMMMMMM.                        .MMM'                ..:ONx;.       .:0XWO;                                           .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                            cMMMMMMMMMMNd'               ,kMMMMMMMMMMW,        .MMMMMMMMMl                  ,dXMMMMMMMMMMMx                          0MMO                  .;l0OKXK00KNWKkl,                                .             .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                             'XMMMMMMMMMMMW0dc;'....,:o0WMMMMMMMMMMMO.         .MMMMMMMMMMNx:'.     ..,:oONMMMMMMMMMMMMMMd     .                     .WMM0o.                  .'..'''.                                      .             .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                               lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,            :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'                             :MMMMK.                                                                             .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                 :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,               'KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo.         .                      cMMMMc                                                                             .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                   .cOWMMMMMMMMMMMMMMMMMMMMMM0l.                   'xNMMMMMMMMMMMMMMMMMMMMMMMMMMKx:.                                    ;WMMW,                                                            .               .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                       .:dOXWMMMMMMMMMMNKkl'                          .:dOXWMMMMMMMMMMMMNKOxl;.                                          .0MMN,                                                          .                .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                              ........                                       .........                                                     cNMMk.                                                       .                 .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                             oWMW:                                                     .                  .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                               lXMWO'                                                                     .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                 'xNMO,                                                                   .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                    'l0NXd.                                                               .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                        .,lc;,..                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .MMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMM.                                                                                                                                                                                                                                          .WMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMW:                                                                                                                                                                                                                                          oKMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMNX'                                                                                                                                                                                                                                        'XWMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMMMK:                                                                                                                                                                                                                                     .cKWMMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMMMWX0o'                                                                                                                                                                                                                                .o0WMMMMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMMMMMMMXKkoc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:odOKWNMMMMMMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMMMMMMMMMMMXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMM.
                            ,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.
                            ,WWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.
                            .KNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.
                            .XNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkkxk0XXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN
                             xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNO,.     .lNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo
                             ,NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX.         ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;
                              ;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK.         .XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXKc
                               ;XNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd        .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNc
                                ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkd;,'.:x0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,
                                 .oNMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo'
                                   .oXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXc.
                                     .ckKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKNNk;.
                                         cO0NKXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0x:.
                                            .;cOxOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkxo:;.
                                                  .. .'.............................................................................................................................................................................................................................



                                                                                                                                           .,cllllllllllllllllllllllllllllllllllllllllloc;
                                                                                                                                           kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx.
                                                                                                                                          .NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN
                                                                                                                                          .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN
                                                                                                                                          .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN
                                                                                                                                          .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN
                                                                                                                                          .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN
                                                                                                                                          .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN
                                                                                                                                          .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN
                                                                                                                                          .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN
                                                                                                                                          'WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX.
                                                                                                                                         'kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:
                                                                                                                    :odkkkkkkkkkkkkkkkkk0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWKxkkkkkkkkkkkkkkkkkxd:.
                                                                                                                   OXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0
                                                                                                                   NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
                                                                                                                  .KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN
                                                                                                                  .cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKo
                                                                                                                     ............................................................................................


EOF 
